#!/usr/bin/env python3
"""
R4 stage A — main runs, paired bootstrap, and the three prespecified sensitivities.
Permutations run separately (stages B and C) because they cost 16 h.

Specification, per ANALYSIS_PLAN.md at fdf7e35:
  X = clinical(5) + corrected-radiomics PCs(20) + FM PCs(30)   W = frozen epoch one-hot
  discrete_treatment=True; RF nuisances 500 / leaf 5 / sqrt / seed 42
  strict OOF: scaler, PCA, both nuisances, forest all fit on training folds only
  saved folds, loaded (not re-derived); bootstrap 2000, arm-stratified, evaluation-only,
  identical resample indices across configurations
"""
import os, sys, json, time
import numpy as np, pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import StratifiedKFold
from econml.dml import CausalForestDML
from joblib import Parallel, delayed
import warnings; warnings.filterwarnings("ignore")

# --- public-release path resolution (the only edits relative to the frozen module; see docs/CODE_MODIFICATIONS.md) ---
RELEASE_ROOT=os.environ.get("JIIM_RELEASE_ROOT", os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")))
DATA=os.environ.get("JIIM_DATA_ROOT", os.path.join(RELEASE_ROOT, "external_data"))   # source data and feature matrices (not redistributed)
ROOT=os.path.join(DATA, "features"); R2=os.path.join(DATA, "features")
R3=os.path.join(RELEASE_ROOT, "reproduction", "splits")   # epoch assignment regenerated by derive_epochs.py
R4=os.path.join(RELEASE_ROOT, "reproduction", "r4_legacy")
CLINICAL_XLSX=os.path.join(DATA, "clinical_and_imaging_info.xlsx")
SEED=42; K=5; NBOOT=2000; PLAN="fdf7e35"
CLIN=["age","tumor_subtype_enc","ethnicity_enc","bmi_group_enc","menopause_enc"]
NUIS=dict(n_estimators=500,min_samples_leaf=5,max_features="sqrt",random_state=SEED)
COH={"her2neg":(0.0,"Paclitaxel"),"her2pos":(1.0,"Paclitaxel + Trastuzumab")}

def load(cohort):
    hv,ctrl=COH[cohort]
    df=pd.read_excel(CLINICAL_XLSX)
    c=df[df.dataset=="ISPY2"]; c=c[c.her2==hv].dropna(subset=["pcr"]).copy()
    c["T"]=(c.nac_agent!=ctrl).astype(int); c["age"]=c.age.fillna(c.age.median())
    for x in ["bmi_group","menopause","ethnicity"]: c[x]=c[x].fillna("unknown")
    for x in ["tumor_subtype","ethnicity","bmi_group","menopause"]:
        c[x+"_enc"]=LabelEncoder().fit_transform(c[x].astype(str))
    c=c.merge(pd.read_csv(f"{R3}/epoch_assignment.csv")[["patient_id","epoch"]],on="patient_id")
    rad=pd.read_csv(f"{R2}/radiomics_{cohort}_binCount64_20260725.csv")
    clip=pd.read_csv(f"{ROOT}/biomedclip_her2neg_reextract_20260725.csv" if cohort=="her2neg" else f"{ROOT}/biomedclip_her2pos_reextract_20260725.csv")
    dino=pd.read_csv(f"{R2}/raddino_{cohort}_reextract_cls_usefast_20260725.csv")
    c=c.merge(rad,on="patient_id").merge(clip,on="patient_id",suffixes=("","_c")).merge(dino,on="patient_id",suffixes=("","_d"))
    cols={"rad":[x for x in rad.columns if x!="patient_id"],
          "clip":[x for x in clip.columns if x!="patient_id"],
          "dino":[x for x in dino.columns if x!="patient_id"]}
    W=pd.get_dummies(c.epoch.astype(int),prefix="ep").values.astype(float)
    return c.reset_index(drop=True),cols,W

CONFIGS={"Clinical only":[], "Clin + Radiomics":[("rad",20)], "Clin + BiomedCLIP":[("clip",30)],
         "Clin + RAD-DINO":[("dino",30)], "Clin + Rad + BiomedCLIP":[("rad",20),("clip",30)],
         "Clin + Rad + RAD-DINO":[("rad",20),("dino",30)]}
PRINCIPAL="Clin + Rad + BiomedCLIP"

def autoc(cate,T,Y):
    i=np.argsort(-cate); Ts,Ys=T[i],Y[i]; nt=nc=0; st=sc=s=0.0
    for j in range(len(cate)):
        if Ts[j]==1: nt+=1; st+=Ys[j]
        else: nc+=1; sc+=Ys[j]
        if nt and nc: s+=st/nt-sc/nc
    return s/len(cate)

def run_config(c,cols,W,blocks,T,Y,folds,use_W=True,discrete=True):
    oof=np.full(len(T),np.nan); eh=np.full(len(T),np.nan)
    for tr,te in folds:
        ss=StandardScaler().fit(c[CLIN].values[tr])
        Xtr=[ss.transform(c[CLIN].values[tr])]; Xte=[ss.transform(c[CLIN].values[te])]
        for key,k in blocks:
            V=np.nan_to_num(c[cols[key]].values.astype(float))
            s2=StandardScaler().fit(V[tr]); p=PCA(k,random_state=SEED).fit(s2.transform(V[tr]))
            Xtr.append(p.transform(s2.transform(V[tr]))); Xte.append(p.transform(s2.transform(V[te])))
        Xtr,Xte=np.hstack(Xtr),np.hstack(Xte)
        Wtr,Wte=(W[tr],W[te]) if use_W else (None,None)
        mt=RandomForestClassifier(**NUIS) if discrete else RandomForestRegressor(**NUIS)
        cf=CausalForestDML(model_y=RandomForestRegressor(**NUIS),model_t=mt,
                           n_estimators=500,min_samples_leaf=20,random_state=SEED,cv=5,
                           discrete_treatment=discrete)
        cf.fit(Y[tr],T[tr],X=Xtr,W=Wtr)
        oof[te]=cf.effect(Xte).flatten()
        Ztr=np.hstack([Xtr,Wtr]) if use_W else Xtr; Zte=np.hstack([Xte,Wte]) if use_W else Xte
        m2=(RandomForestClassifier(**NUIS) if discrete else RandomForestRegressor(**NUIS)).fit(Ztr,T[tr])
        eh[te]=m2.predict_proba(Zte)[:,1] if discrete else m2.predict(Zte)
    return oof,eh

def ediag(e):
    return {"min":float(np.min(e)),"max":float(np.max(e)),
            "q":[float(np.percentile(e,q)) for q in (5,25,50,75,95)],
            "prop_outside_0_1":float(((e<0)|(e>1)).mean()),
            "prop_outside_0.05_0.95":float(((e<0.05)|(e>0.95)).mean())}

def analyse(cohort,label,population,use_W=True,discrete=True,drop_ids=None,njobs=6):
    c,cols,W=load(cohort); T=c["T"].values.astype(int); Y=c["pcr"].values.astype(float)
    folds=list(StratifiedKFold(K,shuffle=True,random_state=SEED).split(np.zeros(len(T)),2*T+Y.astype(int)))
    if drop_ids:
        keep=~c.patient_id.isin(drop_ids).values
        folds=[(tr[keep[tr]],te[keep[te]]) for tr,te in folds]
    t0=time.perf_counter()
    out=Parallel(n_jobs=njobs)(delayed(run_config)(c,cols,W,b,T,Y,folds,use_W,discrete)
                               for b in CONFIGS.values())
    idx=np.concatenate([te for _,te in folds]); idx.sort()
    res={"cohort":cohort,"label":label,"population":population,"n":int(len(idx)),
         "epoch_in_W":use_W,"discrete_treatment":discrete,"plan_commit":PLAN,
         "elapsed_s":round(time.perf_counter()-t0,1),"configs":{}}
    cates={}
    for (name,_),(oof,eh) in zip(CONFIGS.items(),out):
        cates[name]=oof[idx]
        res["configs"][name]={"autoc":float(autoc(oof[idx],T[idx],Y[idx])),
                              "propensity_heldout":ediag(eh[idx])}
    # paired bootstrap: arm-stratified, IDENTICAL indices across configs, evaluation-only
    Ti,Yi=T[idx],Y[idx]; e_i=np.where(Ti==1)[0]; c_i=np.where(Ti==0)[0]
    rng=np.random.default_rng(20260725)
    B={n:[] for n in CONFIGS}
    for _ in range(NBOOT):
        b=np.concatenate([rng.choice(e_i,len(e_i),True),rng.choice(c_i,len(c_i),True)])
        for n in CONFIGS: B[n].append(autoc(cates[n][b],Ti[b],Yi[b]))
    for n in CONFIGS:
        a=np.array(B[n]); res["configs"][n]["ci95"]=[float(np.percentile(a,2.5)),float(np.percentile(a,97.5))]
    res["paired_deltas"]={}
    for comp in ["Clinical only","Clin + Radiomics"]:
        d=np.array(B[PRINCIPAL])-np.array(B[comp])
        p=2*min((d<=0).mean(),(d>=0).mean())
        res["paired_deltas"][f"{PRINCIPAL} - {comp}"]={
            "point":res["configs"][PRINCIPAL]["autoc"]-res["configs"][comp]["autoc"],
            "ci95":[float(np.percentile(d,2.5)),float(np.percentile(d,97.5))],
            "boot_p":float(min(p,1.0))}
    np.savez(f"{R4}/cate_{label}.npz",**{k:v for k,v in cates.items()},T=Ti,Y=Yi)
    return res

if __name__=="__main__":
    os.makedirs(R4,exist_ok=True)   # legacy stage-A entry point; not part of the released pipeline
    runs=[]
    empty=set(pd.read_csv(f"{R3}/epoch_assignment.csv").query("epoch in [1,21]").patient_id)
    for coh in ["her2neg","her2pos"]:
        pop="full_"+coh
        runs.append(("PRIMARY",coh,pop,dict(use_W=True,discrete=True,drop_ids=None)))
        runs.append(("no-epoch diagnostic",coh,pop,dict(use_W=False,discrete=True,drop_ids=None)))
        runs.append(("alt treatment-nuisance spec",coh,pop,dict(use_W=True,discrete=False,drop_ids=None)))
    runs.append(("empty-arm-epoch exclusion sensitivity","her2neg","empty_epoch_exclusion",
                 dict(use_W=True,discrete=True,drop_ids=empty)))
    allres=[]
    for label,coh,pop,kw in runs:
        print(f"\n=== {label} | {coh} | population={pop} ===",flush=True)
        r=analyse(coh,f"{label.replace(' ','_')}__{coh}",pop,**kw); allres.append(r)
        for n,v in r["configs"].items():
            print(f"  {n:26s} AUTOC {v['autoc']:+.4f}  CI [{v['ci95'][0]:+.4f}, {v['ci95'][1]:+.4f}]",flush=True)
        for k,v in r["paired_deltas"].items():
            print(f"  Δ {k:44s} {v['point']:+.4f}  CI [{v['ci95'][0]:+.4f}, {v['ci95'][1]:+.4f}]  p={v['boot_p']:.4f}",flush=True)
        json.dump(allres,open(f"{R4}/r4_stageA_results.json","w"),indent=1)
    print("\nwrote r4_stageA_results.json")
