"""R7 shared loader. Reuses the FROZEN r4_stageA.load() verbatim so feature assembly,
merge order and row order are bit-identical to the frozen R4 pipeline. INPUT ONLY."""
import os, sys, json, hashlib
import numpy as np, pandas as pd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))   # the frozen loader module ships alongside
import r4_stageA as r4a                      # frozen module; __main__ block not executed

SEED     = 42          # model / PCA / split seed, unchanged from R4
BOOTSEED = 20260906    # grf half-sample bootstrap seed, R7-specific
R_BOOT   = 2000
RELEASE_ROOT = os.environ.get("JIIM_RELEASE_ROOT", os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")))
OUT      = os.path.join(RELEASE_ROOT, "reproduction", "rate_primary"); os.makedirs(OUT, exist_ok=True)
EPOCH_CSV = os.path.join(RELEASE_ROOT, "reproduction", "splits", "epoch_assignment.csv")   # regenerated by derive_epochs.py
CLIN     = r4a.CLIN
NUIS     = r4a.NUIS
CONFIGS  = r4a.CONFIGS
REFERENCE = "Clin + Rad + BiomedCLIP"        # historically designated reference configuration
BASELINE  = "Clinical only"

def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""): h.update(b)
    return h.hexdigest()

def split_739(n, seed=SEED):
    """Plain random 50/50 allocation. Y is NOT used. T is NOT used. No stratification."""
    rng = np.random.default_rng(seed)
    perm = rng.permutation(n)
    n_tr = n // 2 + (n % 2)                  # 739 -> 370 train / 369 evaluation
    is_train = np.zeros(n, bool); is_train[perm[:n_tr]] = True
    return is_train
